mybook/bath/urls.py
from django.urls import path
from . import views

app_name='bath'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:member_id>/done/', views.done, name='done'),
    path('reserve/', views.reserve, name='reserve'),
    path('login-user/', views.show_login_user, name='show_login_user'),
]

mybook/mybook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('upload/', include('upload.urls')),
    path('hsapp/', include('hsapp.urls')),
    path('account/', include('account.urls')),
    path('bath/', include('bath.urls')),
    path('foreign/', include('foreign.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mybook/bath/models.py
from django.db import models
from django.utils import timezone


class Member(models.Model):
    name = models.CharField(max_length=40, default='Nobody')
    done = models.BooleanField(default=False)
    reserve_time = models.IntegerField(default=20)

    def __str__(self):
        return self.name

mybook/bath/forms.py
from django import forms
from .models import Member


class ReservationForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ('reserve_time',)

mybook/bath/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.http import HttpResponse
from .models import Member
from .forms import ReservationForm


def index(request):
    members = Member.objects.all().order_by('-done')
    context = {'members': members, 'user': request.user}
    return render(request, 'bath/index.html', context)


def reserve(request):
    member = Member.objects.get(name=request.user.username)
    if request.method == 'POST':
        form = ReservationForm(request.POST, instance=member)
        if form.is_valid():
            member = form.save(commit=False)
            member.save()
            return redirect('bath:index')
    else:
        form = ReservationForm()

    context = {'member': member, 'form': form, }
    return render(request, 'bath/reserve.html', context)


def done(request, member_id):
    member = get_object_or_404(User, pk=member_id)
    member.done = not member.done
    member.save()
    return redirect('bath:index')


def show_login_user(request):
    user = request.user
    return render(request, 'bath/show_login_user.html', {'user': user})

mybook/bath/templates/bath/index.html
{% extends 'bath/base.html' %}

{% block title %}Bath Reservation{% endblock title %}

{% block content %}
<h1 class="border-bottom">
    Bath Reservation: <small>Login: {{ user.username }}</small>

    <div align="right">

        <a href="{% url 'bath:index' %}" class="btn btn-secondary btn-sm">Logout</a>
    </div>
</h1>

    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Name</th>
                <th>Reserved Time</th>
                <th>Done</th>
            </tr>
        </thead>

        <tbody>
            {% for member in members %}
            <tr>
                <td>{{ member.name }}</td>
                <td>{{ member.reserve_time }}</td>
                <td>
                    {% if member.done %}
                        <a href="{% url 'bath:done' member_id=member.id %}" class="btn btn-outline-info">Y</a>
                    {% else %}
                        <a href="{% url 'bath:done' member_id=member.id %}" class="btn btn-outline-danger">N</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{% url 'bath:reserve' %}" class="btn btn-primary btn-sm">Reserve</a>
    <a href="{% url 'bath:show_login_user' %}" class="btn btn-primary btn-sm">ShowUser</a>

{% endblock content %}

mybook/bath/templates/bath/reserve.html
{% extends 'bath/base.html' %}

{% block title %}Reservation Form{% endblock title %}

{% block content %}
    <h1 class="border-bottom">Hi, {{ member.name }}! Reserve your bath time here</h1>
    <form action="{% url 'bath:reserve' %}" method="post">
        {% csrf_token %}
        <label>Reservation Time</label>
        {{ form.reserve_time }}
        <input type="submit" value="Register">
    </form>

{% endblock content %}

mybook/bath/templates/bath/show_login_user.html
{% extends 'bath/base.html' %}
{% block title %}{% endblock title %}

{% block content %}
    <h1>Login User Information</h1><br>
    name:{{ user.username }}
{% endblock content %}