mybook/bath/urls.py
from django.urls import path
from . import views

app_name='bath'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:member_id>/done/', views.done, name='done'),
    path('reserve/', views.reserve, name='reserve'),
    path('login-user/', views.show_login_user, name='show_login_user'),
]

mybook/foreign/urls.py
from django.urls import path
from . import views

app_name = 'foreign'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mybook/mybook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('upload/', include('upload.urls')),
    path('hsapp/', include('hsapp.urls')),
    path('account/', include('account.urls')),
    path('bath/', include('bath.urls')),
    path('foreign/', include('foreign.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mybook/foreign/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    vote = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mybook/foreign/forms.py
from django import forms
from .models import Dealer, Farmer, FieldOfficer



class SearchForm(forms.Form):
    name = forms.CharField(
        initial='',
        label='Name',
        required = False, # 必須ではない
    )
    product = forms.CharField(
        initial='',
        label='Product',
        required=False,  # 必須ではない
    )
    season = forms.CharField(
        initial='',
        label='Season',
        required=False,  # 必須ではない
    )
    location = forms.CharField(
        initial='',
        label='Location',
        required=False,  # 必須ではない
    )

mybook/foreign/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.utils import timezone

from .models import Question, Choice



def index(request):
    latest_question_list = Question.objects.all().order_by('-created_at')[:5]
    context = {'latest_question_list': latest_question_list, }
    return render(request, 'foreign/index.html', context)



def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    choices = Choice.objects.filter(question=question).order_by('choice_text')
    context = {'question': question, 'choices': choices}
    return render(request, 'foreign/detail.html', context)


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'foreign/results.html', {'question': question})
    #return HttpResponse('Results of question %s' % question_id)


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'foreign/detail.html',{
                          'question': question,
                          'error_message': "You didn't select your choice. Select a choice and push Vote!"
                      })

    else:
        selected_choice.vote += 1
        selected_choice.save()
        return redirect('foreign:results', question_id=question_id)
    #return HttpResponse('Vote of question %s' % question_id)

mybook/foreign/templates/foreign/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'foreign/css/bootstrap.min.css' %}">
    {% block extra_css %}{% endblock %}
    <title>{% block title %}My books{% endblock %}</title>
  </head>
  <body>
    <div class="container">
      {% block content %}
      {{ content }}
      {% endblock %}
    </div>
    <script src="{% static 'foreign/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'foreign/js/bootstrap.bundle.min.js' %}"></script>
    {% block extra_js %}{% endblock %}
  </body>
</html>

mybook/foreign/templates/foreign/detail.html
{% extends "foreign/base.html" %}

{% block title %}Question List{% endblock title %}

{% block content %}
<h2 class="mt-4 border-bottom">Question {{ question.id }}: {{ question.question_text }}</h4><br>
<h3><font color="red">{{ error_message }}</font></h3><br>
<a href="{% url 'foreign:index' %}" class="btn btn-primary btn-sm">Home</a>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>Choice</th>
    </tr>
  </thead>
  <form action="{% url 'foreign:vote' question_id=question.id %}" method="post">
    {% csrf_token %}
    <tbody>
      {# {% for choice in choices %} #}
      {% for choice in question.choice_set.all %}
      <tr>
	<td>{{ forloop.counter }}</td>
	<td>
	  <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
	  {{ choice.choice_text }}
	</td>
      </tr>
      {% endfor %}
  </tbody>
</table>
<input type="submit" value="Vote">

{% endblock content %}

mybook/foreign/templates/foreign/index.html
{% extends "foreign/base.html" %}

{% block title %}Question List{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">Question List</h4>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>Question</th>
      <th>Published Date</th>
    </tr>
  </thead>
  <tbody>
    {% for question in latest_question_list %}
    <tr>
      <td>{{ question.id }}</td>
      <td><a href="{% url 'foreign:detail' question_id=question.id %}">{{ question.question_text }}</a></td>
      <td>{{ question.created_at }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}

mybook/foreign/templates/foreign/results.html
{% extends "foreign/base.html" %}

{% block title %}Question List{% endblock title %}

{% block content %}
<h2 class="mt-4 border-bottom">Results| <small>Question {{ question.id }}: {{ question.question_text }}</small></h4><br>
<a href="{% url 'foreign:index' %}" class="btn btn-primary btn-sm">Home</a>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>Choice</th>
      <th>Vote</th>
    </tr>
  </thead>
  
  <tbody>
    {% for choice in question.choice_set.all %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td>{{ choice.choice_text }}</td>
      <td>{{ choice.vote }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<a href="{% url 'foreign:vote' question_id=question.id %}" class="btn btn-secondary btn-sm">Vote again</a>

{% endblock content %}