mybook/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('create_account/', views.CreateAccount, name='create_account'),
]

mybook/bath/urls.py
from django.urls import path
from . import views

app_name='bath'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:member_id>/done/', views.done, name='done'),
    path('reserve/', views.reserve, name='reserve'),
    path('login-user/', views.show_login_user, name='show_login_user'),
]

mybook/hsapp/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views


app_name = 'hsapp'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('dealer_info/', views.DealerInfo.as_view(), name='dealer_info'),
    path('farmer_list/', views.FarmerList.as_view(), name='farmer_list'),
    path('farmer_list/search_results/', views.SearchResultsView.as_view(), name='search_results_list'),
    path('farmer_list/search_test/', views.search_test, name='search_test'),
    path('create_farmer/', views.CreateNewFarmer.as_view(), name='create_farmer'),
    path('product_list/', views.ProductList.as_view(), name='product_list'),
    path('product_detail/<int:pk>/', views.ProductDetail.as_view(), name='product_detail'),
    path('product_in_season/', views.ProductInSeasonList.as_view(), name='product_in_season'),
    path('plant_list/', views.PlantList.as_view(), name='plant_list'),
    path('plant_detail/<int:pk>/', views.PlantDetail.as_view(), name='plant_detail'),
    path('company_list/', views.CompanyList.as_view(), name='company_list'),
    path('company_detail/<int:pk>/', views.CompanyDetail.as_view(), name='company_detail'),
]

mybook/mybook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('upload/', include('upload.urls')),
    path('hsapp/', include('hsapp.urls')),
    path('account/', include('account.urls')),
    path('bath/', include('bath.urls')),
    path('foreign/', include('foreign.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mybook/upload/urls.py
from django.urls import path
from . import views

app_name='upload'
urlpatterns = [
    path('load_csv', views.load_csv, name='load_csv'),
]

mybook/hsapp/models.py
from django.db import models
from django.core.validators import validate_comma_separated_integer_list
from django.utils import timezone


class Dealer(models.Model):
    name = models.CharField(max_length=255)
    location = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Farmer(models.Model):
    phone = models.IntegerField()
    name = models.CharField(max_length=128)
    state_id_number = models.CharField(max_length=128)
    state_id_picture = models.FileField(blank=True)
    birth_date = models.CharField(max_length=128)
    dependents = models.CharField(max_length=255)
    land_size = models.IntegerField(default=0)
    leased_land = models.BooleanField(default=False)
    previous_hs_client = models.BooleanField(default=False)
    location = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class FieldOfficer(models.Model):
    name = models.CharField(max_length=255)
    farmers = models.ManyToManyField(Farmer, blank=True, default=[1])

    def __str__(self):
        return self.name


class VisitFarmer(models.Model):
    farmer = models.ForeignKey(Farmer, on_delete=models.CASCADE, default=1)
    field_officer = models.ForeignKey(FieldOfficer, on_delete=models.CASCADE, default=1)
    done_or_appointment = models.BooleanField(default=False)
    date = models.DateField(default=timezone.now)
    check_in_time = models.TimeField(default=timezone.now)
    check_out_time = models.TimeField(default=timezone.now)


class VisitDealer(models.Model):
    dealer = models.ForeignKey(Dealer, on_delete=models.CASCADE, default=1)
    field_officer = models.ForeignKey(FieldOfficer, on_delete=models.CASCADE, default=1)
    done_or_appointment = models.BooleanField(default=False)
    date = models.DateField(default=timezone.now)
    check_in_time = models.TimeField(default=timezone.now)
    check_out_time = models.TimeField(default=timezone.now)

"""
class Visit(models.Model):
    customer_id = models.CharField(max_length=128)
    fo_id = models.CharField(max_length=128)
    done_or_appointment = models.BooleanField(default=False) # if done: False, appointment: True
    date = models.DateField(default=timezone.now)
    check_in_time = models.IntegerField()
    check_out_time = models.IntegerField()

    def __str__(self):
        return self.date
"""


class Plant(models.Model):
    name = models.CharField(max_length=128)
    species = models.CharField(max_length=128, blank=True)
    season_in = models.IntegerField()   # in month
    season_end = models.IntegerField()  # end month
    #season = models.CharField()      # summer, winter, etc

    def __str__(self):
        return self.name


class Company(models.Model):
    name = models.CharField(max_length=128)
    location = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Product(models.Model):
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE, default=1)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=128)
    quantity = models.IntegerField(default=0)
    price = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class ProspectFarmer(models.Model):
    farmer = models.ForeignKey(Farmer, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=128)
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.name


class Escalation(models.Model):
    farmer = models.ForeignKey(Farmer, on_delete=models.CASCADE, default=1)
    field_officer = models.ForeignKey(FieldOfficer, on_delete=models.CASCADE, default=1)
    tmo_call_required = models.BooleanField(default=True)
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.date


class FarmerPlant(models.Model):
    farmer = models.ForeignKey(Farmer, on_delete=models.CASCADE, default=1)
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE, default=1)
    plant_period = models.DateField(default=timezone.now)
    major = models.BooleanField()  # If the farmer plants this crop as his main crop

    def __str__(self):
        return self.plant.name


class DealerFarmerRelation(models.Model):
    dealer = models.ForeignKey(Dealer, on_delete=models.CASCADE, default=1)
    farmer = models.ForeignKey(Farmer, on_delete=models.CASCADE, default=1)
    close_relation = models.BooleanField(default=False)

    def __str__(self):
        return self.close_relation


class PurchaseHistory(models.Model):
    dealer = models.ForeignKey(Dealer, on_delete=models.CASCADE, default=1)
    farmer = models.ForeignKey(Farmer, on_delete=models.CASCADE, default=1)
    product = models.ForeignKey(Plant, on_delete=models.CASCADE, default=1)
    date = models.DateField(default=timezone.now)
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return self.date


class FarmerInterest(models.Model):
    farmer = models.ForeignKey(Farmer, on_delete=models.CASCADE, default=1)
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE, default=1)
    interested = models.BooleanField(default=False)
    quantity = models.IntegerField(default=0)
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.plant.name


class DealerProduct(models.Model):
    dealer = models.ForeignKey(Dealer, on_delete=models.CASCADE, default=1)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, default=1)
    quantity = models.IntegerField(default=0)
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.dealer.name

mybook/upload/models.py
from django.db import models

# Create your models here.

mybook/hsapp/forms.py
from .models import Farmer, Dealer
from django import forms

class FarmerCreationForm(forms.ModelForm):

    class Meta:
        model = Farmer
        exclude = ()
        static_id_picture = forms.FileField(
            required=False,
        )

mybook/hsapp/views.py
import operator
from functools import reduce

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.db.models import Q
from django.views.generic import TemplateView, CreateView, UpdateView, DetailView
from django.views.generic.list import ListView
from .models import *
from .forms import *
import pandas as pd
from io import TextIOWrapper, StringIO


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'hsapp/home.html'


class CreateNewFarmer(LoginRequiredMixin, CreateView):
    model = Farmer
    form_class = FarmerCreationForm
    template_name = "hsapp/create_farmer.html"
    success_url = reverse_lazy('hsapp:home')


class ProductList(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'hsapp/product_list.html'


class ProductInSeasonList(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'hsapp/product_list.html'

    def get_queryset(self):
        result = super(ProductInSeasonList, self).get_queryset()
        month_now = timezone.now().month
        plants_in_season_candidate = Plant.objects.filter(season_end__gte=month_now)
        plants_in_season = []
        for plant in plants_in_season_candidate:
            s_in = plant.season_in
            s_end = plant.season_end
            if s_in > s_end:
                plants_in_season.append(plant)
            elif s_in <= month_now:
                plants_in_season.append(plant)

        result = result.filter(plant__in=[plant for plant in plants_in_season])

        return result


class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'hsapp/product_detail.html'


class PlantList(LoginRequiredMixin, ListView):
    model = Plant
    template_name = 'hsapp/plant_list.html'


class PlantDetail(LoginRequiredMixin, DetailView):
    model = Plant
    template_name = 'hsapp/plant_detail.html'


class CompanyList(LoginRequiredMixin, ListView):
    model = Company
    template_name = 'hsapp/company_list.html'


class CompanyDetail(LoginRequiredMixin, DetailView):
    model = Company
    template_name = 'hsapp/company_detail.html'


class DealerInfo(LoginRequiredMixin, ListView):
    template_name = 'hsapp/dealer_info.html'
    model = Dealer
    context_object_name = 'dealers'
    def get_queryset(self):
        dealers = Dealer.objects.all()
        return dealers


class FarmerList(LoginRequiredMixin, ListView):
    model = Farmer
    context_object_name = 'farmers'
    template_name = 'hsapp/farmer_list.html'
    #paginate_by = 10

    def get_queryset(self):
        login_user = self.request.user
        farmers = Farmer.objects.all()
        if login_user.groups.filter(name='FO').exists() and (not login_user.is_superuser):
            name = login_user.first_name
            fo = FieldOfficer.objects.get(name=name)
            farmers = fo.farmers.all()

        if "order_by" in self.request.GET:
            order_key = self.request.GET.get('order_by')
            farmers = farmers.order_by(order_key)
        return farmers


class SearchResultsView(ListView):
    model = Farmer
    context_object_name = 'farmers'
    template_name = 'hsapp/farmer_list.html'
    paginate_by = 10

    def get_queryset(self):
        result = super(SearchResultsView, self).get_queryset()

        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            condition_name = reduce(operator.or_, [Q(name__icontains=q) for q in query_list])
            condition_product = reduce(operator.or_, [Q(product__icontains=q) for q in query_list])

            result = result.filter(condition_name & condition_product)

        return result


def search_test(request):
    farmers = Farmer.objects.all()
    query = ''
    query_list = ''
    if 'q' in request.GET:
        query = request.GET.get('q')
        query_list = query.split()


    template_name = 'hsapp/farmer_list.html'
    context = {'farmers': farmers}
    #return render(request, template_name, context)
    return HttpResponse(query_list)

mybook/hsapp/templates/hsapp/company_detail.html
{% extends 'adminlte/base.html' %}

{% load static %}

{% block title %}Company{% endblock title %}

{% block content %}
    <h2><a href="#">Company Detail</a></h2>

    <p>Company: {{ company.name }}</p>
    <p>location: {{ company.location }}</p>
    {% for product in company.product_set.all %}
        <p>Product: {{ product.name }} -- {{ product.plant.name }} [{{ product.plant.season_in }} - {{ product.plant.season_end }}]</p>
    {% endfor %}

{% endblock content %}

mybook/hsapp/templates/hsapp/company_list.html
{% extends 'hsapp/base.html' %}

{% load static %}

{% block title %}Dealer List{% endblock title %}

{% block content %}
    <h2><a href="{% url 'hsapp:company_list' %}">Company List</a></h2>
    <form method="get" action="{% url 'hsapp:company_list' %}">
        <input type="text" value="" name="order_by">
        <input type="submit" value="Sort">
    </form>
    <br>
    <!--
    <form method="get" action="{% url 'hsapp:search_results_list' %}">
        <input type="test" name="q" placeholder="Search...">
        <input type="submit" value="Search">
    </form>
    --->

    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Company</th>
                <th><a href="#">Location</a></th>
                <th><a href="{% url 'hsapp:product_list' %}">Products</a></th>
            </tr>
        </thead>
        <tbody>
            {% for company in company_list%}
            <tr>
                <td>{{ company.id }}</td>
                <td>{{ company.name }}</td>
                <td><a href="#">{{ company.location }}</a></td>
                <td>
                    {% for product in company.product_set %}
                    <a href="{% url 'product_detail' pk=product.id %}">{{ product.name }}</a>
                    {% endfor %}
                </td>
            </tr>
            {% endfor %}
        </tbody>

    </table>

{% endblock content %}

mybook/hsapp/templates/hsapp/create_farmer.html
{% extends 'hsapp/base.html' %}
{% load static %}
{% block title %}Create Farmer{% endblock title %}
{% block content %}

    <h2>Create a new Farmer</h2>
    <hr>
    <form method="post" action="{% url 'hsapp:create_farmer' %}">
        {% csrf_token %}

        <table>
            {{ form.as_table }}
        </table>
        <button type="submit">Save</button>
    </form>

{% endblock content %}

mybook/hsapp/templates/hsapp/dealer_info.html
{% extends 'adminlte/base.html' %}

{% block title %}Dealer Information{% endblock title %}

{% block content %}
    dealer list --- name, location, products stock(name, qty, season)[competing or not], HS products available(name, qty, season)
    {% include 'hsapp/dealer_list.html' %}

<br>    past visits calendar --- dealer_name, spent time  >>> google-calendar?
<br>    visiting calendar --- dealer_name, location       >>> google-calendar?
<br>    dealer - competing products list
<hr>
<br>    select a dealer button
<br>    show the dealer detail
<br>    edit dealer information

        Field officer
            visit n
                date, spent time, which dealer visited



{% endblock content %}

mybook/hsapp/templates/hsapp/dealer_list.html
{% extends 'hsapp/base.html' %}

{% load static %}

{% block title %}Dealer List{% endblock title %}

{% block content %}
    <h2><a href="{% url 'hsapp:dealer_info' %}">Dealer List</a></h2>
    <form method="get" action="{% url 'hsapp:dealer_info' %}">
        <input type="text" value="" name="order_by">
        <input type="submit" value="Sort">
    </form>
    <br>
    <!--
    <form method="get" action="{% url 'hsapp:search_results_list' %}">
        <input type="test" name="q" placeholder="Search...">
        <input type="submit" value="Search">
    </form>
    --->

    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Products Stock</th>
                <th>HS products available</th>
                <th>Location</th>
            </tr>
        </thead>
        <tbody>
            {% for dealer in dealers%}
            <tr>
                <td>{{ dealer.id }}</td>
                <td>{{ dealer.name }}</td>
                <td>{{ farmer.location }}</td>
            </tr>
            {% endfor %}
        </tbody>

    </table>

{% endblock content %}

mybook/hsapp/templates/hsapp/farmer_list.html
{% extends 'hsapp/base.html' %}

{% load static %}

{% block title %}Farmer List{% endblock title %}

{% block content %}
<h2>Farmer List</h2>
<form method="get" action="{% url 'hsapp:farmer_list' %}">
    <input type="text" value="" name="order_by">
    <input type="submit" value="Sort">
</form>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Product</th>
            <th>Season</th>
            <th>Location</th>
            <th>Officers</th>
        </tr>
    </thead>
    <tbody>
        {% for farmer in farmers %}
        <tr>
            <td>{{ farmer.id }}</td>
            <td>{{ farmer.name }}</td>
            <td>{{ farmer.product }}</td>
            <td>{{ farmer.season }}</td>
            <td>{{ farmer.location }}</td>
            <td>{% for officer in farmer.fieldofficer_set.all %}{{ officer.name }}, {% endfor %}</td>
        </tr>
        {% endfor %}
    </tbody>

</table>

{% include 'hsapp/pagination.html' %}

{% endblock content %}

mybook/hsapp/templates/hsapp/home.html
{% extends 'adminlte/base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}

    <div><a href="{% url 'hsapp:farmer_list' %}">Farmer List</a></div>
    <div><a href="{% url 'hsapp:create_farmer' %}">Create new farmer</a></div>
    <div><a href="#">Publish data for dealers</a></div>
    <div><a href="#">Norma</a></div>
    <div><a href="{% url 'hsapp:product_in_season' %}">Products in the season</a></div>
    <div><a href="{% url 'hsapp:product_list' %}">Product List</a></div>
    <div><a href="{% url 'hsapp:plant_list' %}">Plant List</a></div>
    <div><a href="{% url 'hsapp:company_list' %}">Company List</a></div>

    <hr><br>
    <div><a href="{% url 'upload:load_csv' %}">Upload data</a></div>
    <p><a href="{% url 'account:logout' %}">Logout</a></p>

{% endblock content %}

mybook/hsapp/templates/hsapp/pagination.html
<nav aria-label="Page navigation example">
{% if is_paginated %}
  <ul class="pagination justify-content-center pagination-lg g-mt-28 g-mb-28">

    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
        <li class="disabled"><a href="#" class="page-link"><span>&laquo;</span></a></li>
    {% endif %}

    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
          <li class="page-item active"><a class="page-link" href="#"><span>{{ i }} <span class="sr-only">(current)</span></span></a></li>
      {% else %}
        <li><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
        <li class="disabled"><a href="#" class="page-link"><span>&raquo;</span></a></li>
    {% endif %}

  </ul>
{% endif %}
</nav>

mybook/hsapp/templates/hsapp/pagination2.html
<nav aria-label="Page navigation example">

    <ul class="pagination justify-content-center pagination-lg g-mt-28 g-mb-28">
        <!-- 前へ の部分 -->
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="{{ page_obj.previous_page_number }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        <!-- 数字の部分 -->
        {% for num in page_obj.paginator.page_range %}
            {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}

                {% if page_obj.number == num %}
                    <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="{{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endif %}
        {% endfor %}

        <!-- 次へ の部分 -->
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="{{ page_obj.next_page_number }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>

</nav>

mybook/hsapp/templates/hsapp/plant_detail.html
{% extends 'adminlte/base.html' %}

{% load static %}

{% block title %}Plant{% endblock title %}

{% block content %}
    <h2><a href="#">Plant Detail</a></h2>

    <p>Plant: {{ plant.name }}</p>
    <p>Species: {{ plant.species }}</p>
    <p>Season: {{ plant.season_in }} - {{ plant.season_end }}</p>
    {% for farmer in plant.farmerplant_set.all %}
        <p>Farmer: {{ farmer.name }} </p>
    {% endfor %}
    {% for farmer in plant.farmerinterest_set.all %}
        <p>Which farmers are interested?: {{ farmer }}</p>
    {% endfor %}
{% endblock content %}

mybook/hsapp/templates/hsapp/plant_list.html
{% extends 'hsapp/base.html' %}

{% load static %}

{% block title %}Dealer List{% endblock title %}

{% block content %}
    <h2><a href="{% url 'hsapp:plant_list' %}">Plant List</a></h2>
    <form method="get" action="{% url 'hsapp:plant_list' %}">
        <input type="text" value="" name="order_by">
        <input type="submit" value="Sort">
    </form>
    <br>
    <!--
    <form method="get" action="{% url 'hsapp:search_results_list' %}">
        <input type="test" name="q" placeholder="Search...">
        <input type="submit" value="Search">
    </form>
    --->

    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th><a href="#">Plant</a></th>
                <th><a href="#">Species</a></th>
                <th>Season_in</th>
                <th>Season_end</th>
            </tr>
        </thead>
        <tbody>
            {% for plant in plant_list%}
            <tr>
                <td>{{ plant.id }}</td>
                <td><a href="{% url 'hsapp:plant_detail' pk=plant.id %}">{{ plant.name }}</a></td>
                <td><a href="#">{{ plant.species }}</a></td>
                <td>{{ plant.season_in }}</td>
                <td>{{ plant.season_end }}</td>
            </tr>
            {% endfor %}
        </tbody>

    </table>

{% endblock content %}

mybook/hsapp/templates/hsapp/product_detail.html
{% extends 'adminlte/base.html' %}

{% load static %}

{% block title %}Dealer List{% endblock title %}

{% block content %}
    <h2><a href="#">Product Detail</a></h2>

    <p>Product: {{ product.name }}</p>
    <p>Plant: {{ product.plant.name }}</p>
    <p>Company: {{ product.company.name }}</p>
    <p>Price: {{ product.price }} (x {{ product.quantity }})</p>
    {% for dealer_product in product.dealerproduct_set.all %}
        <p>Dealer: {{ dealer_product.dealer.name }} [{{ dealer_product.quantity }}] -- {{ dealer_product.date }}</p>
    {% endfor %}

{% endblock content %}

mybook/hsapp/templates/hsapp/product_list.html
{% extends 'hsapp/base.html' %}

{% load static %}

{% block title %}Product List{% endblock title %}

{% block content %}
    <h2><a href="{% url 'hsapp:product_list' %}">Product List</a></h2>
    <form method="get" action="{% url 'hsapp:product_list' %}">
        <input type="text" value="" name="order_by">
        <input type="submit" value="Sort">
    </form>
    <br>
    <!--
    <form method="get" action="{% url 'hsapp:search_results_list' %}">
        <input type="test" name="q" placeholder="Search...">
        <input type="submit" value="Search">
    </form>
    --->

    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Product</th>
                <th><a href="{% url 'hsapp:plant_list' %}">Plant</a></th>
                <th><a href="{% url 'hsapp:company_list' %}">company</a></th>
                <th>Price</th>
                <th>Quantity</th>
            </tr>
        </thead>
        <tbody>
            {% for product in product_list%}
            <tr>
                <td>{{ product.id }}</td>
                <td>{{ product.name }}</td>
                <td><a href="{% url 'hsapp:plant_detail' pk=product.plant.id %}">{{ product.plant.name }}</a></td>
                <td><a href="{% url 'hsapp:company_detail' pk=product.company.id %}">{{ product.company.name }}</a></td>
                <td>{{ product.price }}</td>
                <td>{{ product.quantity }}</td>
            </tr>
            {% endfor %}
        </tbody>

    </table>

{% endblock content %}

mybook/hsapp/templates/hsapp/upload.html
{% extends "adminlte/base.html" %}
{% load static %}
{% block title %}Data Upload{% endblock %}
{% block extrahead %}
<script>
$(function(){
  $('.dropify').dropify();
})
</script>
{% endblock %}

{% block content %}
<h3>Upload</h3>
<form action="{% url 'hsapp:upload' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="file" class="dropify" data-default-file="Choose upload file" name="csv">
  <button type="submit" class="btn" name="button">Upload</button>
</form>

<p>debug: {{ key }}</p>
<p>debug: {{ request_file }}</p>
{% endblock content %}